CREATE DATABASE assms;

USE assms;

CREATE TABLE customer_details(
	ID INT PRIMARY KEY,
    CNAME VARCHAR(50),
    ADDRESS VARCHAR(150),
    PH_NO VARCHAR(20),
    EMAIL VARCHAR(50),
    DL_NO VARCHAR(15),
    VEHICLE_NO VARCHAR(20),
    SCHEDULE_DATE DATE,
    SCHEDULE_TIME TIME,
    SCHEDULE_DURATION TIME,
    SERVICE_TYPE VARCHAR(200)
    );
    
    
CREATE TABLE staffdatabase(
  ID INT PRIMARY KEY,
  SNAME VARCHAR(50),
  ADDRESS VARCHAR(150),
  EMAIL VARCHAR(50),
  USERNAME VARCHAR(50),
  PASSWD VARCHAR(50)
  );
